cms.ReqExp.Var("operatorID", cms.Yigo2MidExp.GetLoginOperator());
cms.ActionExp.Data( cms.DataExp.PagingQuery("
SELECT wi.topic,
       wi.EmpID,
       wi.DeptID,
       wi.workItemName,
       wi.workitemid,
       wi.creatTime,
       wi.ProcessKey,
       wi.formkey,
       wi.oid,
       j.name operatorname,
       FLOOR (SYSDATE - wi.CreatTime) daytime,
       CEIL (
          ( (SYSDATE - wi.CreatTime) - FLOOR (SYSDATE - wi.CreatTime)) * 24)
          hourtime
  FROM (SELECT m.topic,
               m.EmpID,
               m.DeptID,
               l.workItemName,
               i.instanceID,
               p.workitemid,
               l.creatTime,
               i.ProcessKey,
               i.formkey,
               i.oid
          FROM (SELECT *
                  FROM WF_Participator
                 WHERE OperatorID = ${operatorID}) p
               JOIN BPM_Log l ON p.workitemid = l.workitemid
               JOIN bpm_workiteminfo w ON p.workitemid = w.workitemid
               JOIN BPM_INSTANCE i ON w.instanceID = i.instanceID
               JOIN BPM_Log lp
                  ON     w.parentworkitemid = lp.workitemid
                     AND lp.AuditResult = 0
               JOIN BPM_Migration m ON i.OID = m.BillOID) wi
       LEFT JOIN SYS_Operator j ON j.EmpID = wi.EmpID
",5,cms.ReqExp.Var("pageNo")));
cms.ActionExp.Viewer("json");