cms.ReqExp.Var("operatorID", cms.Yigo2MidExp.GetLoginOperator());
cms.ActionExp.Data( cms.DataExp.PagingQuery("
        	SELECT i.formkey,
       i.oid,
       m.Topic,
       case when l.CreatTime is null then w.creatTime else l.creatTime end creatTime,
       p.workItemID,
       i.instanceid,
       case when l.workItemName is null then w.workItemName else l.workItemName end workItemName,
       j.name operatorname,
          floor(SYSDATE - (case when l.CreatTime is null then w.creatTime else l.creatTime end)) daytime,
          CEIL(((SYSDATE- (case when l.CreatTime is null then w.creatTime else l.creatTime end))-floor(SYSDATE - (case when l.CreatTime is null then w.creatTime else l.creatTime end))) * 24) hourtime
  FROM (SELECT *
          FROM WF_Participator
         WHERE OperatorID = ${operatorID}) p
       JOIN BPM_Log l ON p.WorkitemID = l.WorkitemID
       JOIN bpm_workiteminfo wi ON p.WorkitemID = wi.WorkitemID
       JOIN BPM_Instance i ON l.instanceID = i.instanceID
       JOIN BPM_Migration m ON i.OID = m.BillOID
       LEFT JOIN SYS_Operator j ON j.EmpID = m.EmpID
       LEFT JOIN wf_workitem w ON w.workitemid = l.workitemid
       WHERE w.workitemstate != 3 and not exists (select * from BPM_Log lp
                  where wi.parentworkitemid = lp.workitemid
                     AND lp.AuditResult = 0)
    Order by creatTime desc
",5,cms.ReqExp.Var("pageNo")));
cms.ActionExp.Viewer("json");