cms.PageExp.Local('EmpID',oa.TodoMidExp.queryEmpIDByID(cms.Yigo2MidExp.GetLoginOperator()));
cms.PageExp.Local(
	"data",
    cms.DataExp.QueryList("
		select * from (select a.Topic,a.UrgencyDeg,a.OID,DATE_FORMAT(a.StartTime,'%Y-%m-%d  %H:%i') as starttime,h.name as CREATOR,r.name as addre
		from OA_MeetingInSide_h a LEFT JOIN oa_employee_h h on a.empid=h.oid LEFT JOIN oa_meetingroom_h r on r.oid=a.meetingroom 
		where a.Status=1200 and Participants like '%"&cms.PageExp.Local('EmpID')&"%' order by billdate desc) h ORDER BY h.StartTime desc limit 5
    ")
)