cms.PageExp.Local("operatorID", cms.Yigo2MidExp.GetLoginOperator());
cms.PageExp.Local(
	"data",
    oa.TodoMidExp.queryListByTop("
		select * from (select a.Topic, a.OID,a.EmpID,a.DeptID,a.UrgencyDeg,a.MeetingRoom,a.MeetingType,a.StartTime,a.EndTime,a.Status,a.AllDay 
from OA_MeetingInSide_h a JOIN OA_ParticipatorIDs_D b ON a.OID=b.SOID WHERE b.OptType=10 and b.OptID = ${operatorID} order by billdate desc) h ORDER BY h.StartTime desc",5
    )
)