cms.PageExp.Local("operatorID", cms.Yigo2MidExp.GetLoginOperator());
cms.PageExp.Local('EmpID',oa.TodoMidExp.queryEmpIDByID(cms.Yigo2MidExp.GetLoginOperator()));
cms.PageExp.Local(
	"COUNT_TODO",cms.DataExp.QueryList("SELECT count(*) as countQty FROM
          (select 
      w.workItemID
      from WF_Workitem w 
      join WF_Participator p on w.WorkitemID=p.WorkitemID 
      join BPM_Log l on w.WorkitemID=l.WorkitemID 
      join bpm_workiteminfo wi on w.WorkitemID=wi.WorkitemID 
      join BPM_Instance i on  l.instanceID=i.instanceID
      join BPM_Migration m on  i.OID=m.BillOID
      where p.OperatorID=${operatorID})")
);
cms.PageExp.Local(
	"COUNT_REJECT",cms.DataExp.QueryList("SELECT count(*) as countQty FROM 
      (SELECT w.WorkitemID FROM WF_Workitem w
          JOIN BPM_Log l ON w.WorkitemID = l.WorkitemID
          JOIN bpm_workiteminfo wi ON w.WorkitemID = wi.WorkitemID
          JOIN BPM_Instance i ON l.instanceID = i.instanceID
          JOIN BPM_Migration m ON i.OID = m.BillOID
          WHERE m.Billcreator = ${operatorID} AND i.OID = m.Billoid AND w.AuditResult = 0) k")
);
cms.PageExp.Local(
	"COUNT_FOCUS",cms.DataExp.QueryList("SELECT count(*) as countQty FROM(select l.workitemid
        from bpm_instance i 
        join BPM_migration m on i.oid = m.billoid 
        join bpm_log l on i.instanceid = l.instanceid 
        join oa_feedback f on f.workitemid = l.workitemid 
        where f.operator=${operatorID} and f.feedbacktype = 40
        )j")
);cms.PageExp.Local(
	"COUNT_SEND",cms.DataExp.QueryList("SELECT count(*) as countQty FROM(SELECT w.WorkitemID
    FROM wf_workitem w
         JOIN bpm_workiteminfo bw ON w.WorkitemID = bw.WorkitemID
         JOIN bpm_instance i ON bw.InstanceID = i.InstanceID
         JOIN BPM_migration m ON i.OID = m.BillOID
         WHERE  m.BillCreator = ${operatorID} and BillStatus<1200
         AND bw.WorkitemID IN (  SELECT MAX (WorkitemID) FROM bpm_workiteminfo bpw GROUP BY bpw.InstanceID) ORDER BY creattime DESC 
)j")
);