cms.PageExp.Local('userid',cms.Yigo2MidExp.GetLoginOperator());
cms.PageExp.Local(
    'data',
    cms.DataExp.QueryList({
      SELECT onews.oid as id, onh.name AS col1,onews.topic as col2 ,sys.name  as col3,onews.CreateTime AS col4 ,onews.newscontent as mynews FROM 
      oa_newsdraft_h  onews left join oa_newstype_h onh on onh.oid=onews.newstypeid   left join sys_operator  sys on  sys.oid=onews.Creator where  onews.oid=${id} 
}));
cms.PageExp.Local('newsview','true');