cms.PageExp.Local("operatorID", cms.Yigo2MidExp.GetLoginOperator());
cms.PageExp.Local(
    "mydata",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname from OA_MyWorkflow a join OA_WorkflowType_D b on a.SrcDtlOID=b.oid where a.operator ="+cms.PageExp.Local("operatorID")+" order by b.soid,b.OrderNum,b.Sequence","TSL/TSL_Approval/ExtendBus")
);
cms.PageExp.Local(
    "parentdata",cms.DataExp.QueryList("select DISTINCT(a.oid) oid,a.Name,a.code,a.OrderNum from OA_WorkflowType_H a join OA_WorkflowType_D b on b.soid = a.oid where b.iscommon=1 order by a.OrderNum,a.Code")
);
cms.PageExp.Local(
    "data",cms.DataExp.QueryList("select b.oid,b.soid,b.BillKey,b.billname,b.workflowid,b.workflowkey,COALESCE(b.iscommon,0) iscommon from OA_WorkflowType_D b where b.iscommon=1 order by b.soid,b.OrderNum,b.Sequence")
);