cms.PageExp.Local("formID",cms.PageExp.UrlVar("formID"));
var suffix=oa.TodoMidExp.getSuffixByLanguage();
if(suffix!=""){
  suffix="_"+suffix;
}
var entryPath=cms.PageExp.Local("entryPath");
var where='';
cms.PageExp.Local("flowwhere",where);
if(cms.PageExp.Local("enableQuery")==1){
  if(cms.PageExp.UrlVar("flowwhere")){
      where=cms.PageExp.UrlVar("flowwhere");
      cms.PageExp.Local("flowwhere",where);
      where=" and billname" + suffix + " like '%"+where+"%' ";
  }
}
var areawhere='';
cms.PageExp.Local("areawhere",where);
if(cms.PageExp.Local("enableQuery")==1){
  if(cms.PageExp.UrlVar("areawhere")){
      areawhere=cms.PageExp.UrlVar("areawhere");
      cms.PageExp.Local("areawhere",areawhere);
      areawhere=" and name" + suffix + "='"+areawhere+"' ";
  }
}
cms.PageExp.Local("operatorID", cms.Yigo2MidExp.GetLoginOperator());
if(where==""){
  cms.PageExp.Local(
      "mydata",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_MyWorkflow a join OA_WorkflowType_D b on a.SrcDtlOID=b.oid where a.operator ="+cms.PageExp.Local("operatorID")+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
  );
  if(areawhere==""){
    cms.PageExp.Local(
        "parentdata",cms.DataExp.QueryList("select t.oid,t.Name" + suffix + " as name from OA_WorkflowType_H t where 1=2 order by t.OrderNum,t.Code")
    );
    cms.PageExp.Local(
        "data",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_WorkflowType_D b where 1=2 order by b.soid,b.OrderNum,b.Sequence",entryPath)
    );
  }else{
    cms.PageExp.Local(
        "parentdata",cms.DataExp.QueryList("select t.oid,t.Name" + suffix + " as name from OA_WorkflowType_H t where 1=1 "+areawhere+" order by t.OrderNum,t.Code")
    );
    cms.PageExp.Local(
        "data",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_WorkflowType_D b join OA_WorkflowType_H h on b.soid=h.oid where 1=1 "+areawhere+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
    );
  }
}else{
cms.PageExp.Local(
    "mydata",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_MyWorkflow a join OA_WorkflowType_D b on a.SrcDtlOID=b.oid where a.operator ="+cms.PageExp.Local("operatorID")+where+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
);
cms.PageExp.Local(
    "parentdata",cms.DataExp.QueryList("select t.oid,t.Name" + suffix + " as name from OA_WorkflowType_H t where exists(select soid from OA_WorkflowType_D d where d.soid=t.oid "+where+") order by t.OrderNum,t.Code")
);
cms.PageExp.Local(
    "data",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_WorkflowType_D b where 1=1 "+where+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
);
}