cms.PageExp.Local("formID",cms.PageExp.UrlVar("formID"));
var suffix=oa.TodoMidExp.getSuffixByLanguage();
if(suffix!=""){
  suffix="_"+suffix;
}
var entryPath=cms.PageExp.Local("entryPath");
var where='';
cms.PageExp.Local("flowwhere",where);
if(cms.PageExp.UrlVar("flowwhere")){
  	where=cms.PageExp.UrlVar("flowwhere");
  	cms.PageExp.Local("flowwhere",where);
   	where=" and billname" + suffix + " like '%"+where+"%' ";
}
cms.PageExp.Local("operatorID", cms.Yigo2MidExp.GetLoginOperator());
if(where==""){
cms.PageExp.Local(
    "mydata",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_MyWorkflow a join OA_WorkflowType_D b on a.SrcDtlOID=b.oid where a.operator ="+cms.PageExp.Local("operatorID")+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
);
cms.PageExp.Local(
    "parentdata",cms.DataExp.QueryList("select t.oid,t.Name" + suffix + " as name from OA_WorkflowType_H t order by t.OrderNum,t.Code")
);
cms.PageExp.Local(
    "data",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_WorkflowType_D b order by b.soid,b.OrderNum,b.Sequence",entryPath)
);
}else{
cms.PageExp.Local(
    "mydata",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_MyWorkflow a join OA_WorkflowType_D b on a.SrcDtlOID=b.oid where a.operator ="+cms.PageExp.Local("operatorID")+where+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
);
cms.PageExp.Local(
    "parentdata",cms.DataExp.QueryList("select t.oid,t.Name" + suffix + " as name from OA_WorkflowType_H t where exists(select soid from OA_WorkflowType_D d where d.soid=t.oid "+where+") order by t.OrderNum,t.Code")
);
cms.PageExp.Local(
    "data",oa.TodoMidExp.getWorkflowEntry("select b.oid,b.soid,b.BillKey,b.billname" + suffix + " as billname from OA_WorkflowType_D b where 1=1 "+where+" order by b.soid,b.OrderNum,b.Sequence",entryPath)
);}