create table BOKEDEE_INTERFACE_STATUSLOG
(
  ID             VARCHAR2(50) NOT NULL primary key,
  STARTTIMESTAMP TIMESTAMP(6),
  ENDTIMESTAMP   TIMESTAMP(6),
  USETIMESTAMP   NUMBER default 0,
  TRANSFERDATASIZE FLOAT,
  STATUS         NUMBER,
  INTERFACEID    VARCHAR2(150),
  SERVICEID      VARCHAR2(150),
  INTERFACEDESC  VARCHAR2(500),
  SERVICEDESC    VARCHAR2(500),
  INTERFACENAME  VARCHAR2(200),
  SERVICENAME    VARCHAR2(200),
  FLAG           NUMBER default 0
);
create table BOKEDEE_INTERFACE_DETLOG
(
  ID                  VARCHAR2(50) not null,
  TRANSFORMER_NAME    VARCHAR2(200),
  PROCESS_DATETIME    TIMESTAMP(6),
  PAYLOAD_TYPE        VARCHAR2(150),
  ISNORMAL            NUMBER,
  PAYLOAD_CONTENT     BLOB,
  INBOUND_PROPERTY    BLOB,
  SESSION_PROPERTY    BLOB,
  OUTBOUND_PROPERTY   BLOB,
  INVOCATION_PROPERTY BLOB
);
create index BOKEDEE_STATUSLOG_index on BOKEDEE_INTERFACE_STATUSLOG(STARTTIMESTAMP,ENDTIMESTAMP,USETIMESTAMP,INTERFACEID,SERVICEID);
create index BOKEDEE_DETLOG_index on BOKEDEE_INTERFACE_DETLOG(ID)