CREATE TABLE [BOKEDEE_INTERFACE_STATUSLOG]
(
	[ID] [varchar](50) NOT NULL primary key,
	[STARTTIMESTAMP] [datetime] NULL,
	[ENDTIMESTAMP] [datetime] NULL,
	[USETIMESTAMP] [int] NULL default 0,
	[TRANSFERDATASIZE] [FLOAT],
	[STATUS] [int] NULL,
	[INTERFACEID] [varchar](150) NULL,
	[SERVICEID] [varchar](150) NULL,
	[INTERFACEDESC] [varchar](500) NULL,
	[SERVICEDESC] [varchar](500) NULL,
	[INTERFACENAME] [varchar](200) NULL,
	[SERVICENAME] [varchar](200) NULL,
	[FLAG] [int] NULL default 0
);
create table [BOKEDEE_INTERFACE_DETLOG]
(
	  [ID] 				   [varchar](50) NOT NULL,
	  [TRANSFORMER_NAME]   [varchar](200) NULL,
	  [PROCESS_DATETIME]   [datetime] NULL,
	  [PAYLOAD_TYPE]       [varchar](150) NULL,
	  [ISNORMAL]           [int] NULL,
	  [PAYLOAD_CONTENT]    [image] NULL,
	  [INBOUND_PROPERTY]   [image] NULL,
	  [SESSION_PROPERTY]   [image] NULL,
	  [OUTBOUND_PROPERTY]  [image] NULL,
	  [INVOCATION_PROPERTY][image] NULL
);
create index BOKEDEE_STATUSLOG_index on BOKEDEE_INTERFACE_STATUSLOG(STARTTIMESTAMP,ENDTIMESTAMP,USETIMESTAMP,INTERFACEID,SERVICEID);
create index BOKEDEE_DETLOG_index on BOKEDEE_INTERFACE_DETLOG(ID)