CREATE TABLE BOKEDEE_AUTHORIZATIONUSERINFO(
	USERID VARCHAR(50),
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	CREATETIME VARCHAR(50),
	UPDATETIME VARCHAR(50),
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	GRADE NUMBER(32),
	FLAG NUMBER(32)
);
CREATE TABLE BOKEDEE_AUTHORIZATIONAPPINFO(
	APPID VARCHAR(50),
	APPKEY VARCHAR(30),
	APPSECRET VARCHAR(50),
	APPNAME VARCHAR(30),
	PROVIDER VARCHAR(30),
	CREATETIME VARCHAR(50),
	UPDATETIME VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	FLAG NUMBER(32)
);
CREATE TABLE BOKEDEE_AUTHORIZATIONLINK(
	USERID VARCHAR(50),
	APPID VARCHAR(50)
);
CREATE TABLE BOKEDEE_ACCESSTOKENINFO(
	USERNAME VARCHAR(30),
	APPKEY VARCHAR(30),
	ACCESSTOKEN VARCHAR(50),
	SCOPE VARCHAR(4000),
	STARTTIME VARCHAR(50),
	ENDTIME VARCHAR(50),
	STARTSTAMP VARCHAR(50),
	ENDSTAMP VARCHAR(50),
	UPDATETIME VARCHAR(50),
	CODE VARCHAR(50),
	FLAG NUMBER(32)
);
INSERT INTO BOKEDEE_AUTHORIZATIONUSERINFO (USERID,USERNAME,PASSWORD,CREATETIME,UPDATETIME,NAME,DESCRIPTION,GRADE,FLAG)VALUES(10000,'bokedee','ad2a91450b80f2839ab343d12aa8a4d3',TO_CHAR(SYSDATE,'yyyy-MM-dd HH:mm:ss'),TO_CHAR(SYSDATE,'yyyy-MM-dd HH:mm:ss'),'admin','',5,0);